version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # .NET API
      - "5001:5001"  # HTTPS
    volumes:
      - .:/app
    depends_on:
      - postgres
      - mongodb
    environment:
      - ConnectionStrings__Postgres=Host=postgres;Database=devdb;Username=devuser;Password=devpassword
      - ConnectionStrings__Mongo=mongodb://mongouser:mongopassword@mongodb:27017

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
