version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    depends_on:
      - postgres
      - mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=crypto_tracker;Username=postgres;Password=postgres
      - ConnectionStrings__Mongo=mongodb://mongo:27017/crypto_tracker
    networks:
      - dev_network
    ports:
      - "5000:5000"

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ../frontend:/app
  #     - /app/node_modules
  #   working_dir: /app
  #   command: ["npm", "run", "start"]
  #   ports:
  #     - "4200:4200"
  #   networks:
  #     - dev_network
  #   depends_on:
  #     - backend

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crypto_tracker
    ports:
      - "5432:5432"
    networks:
      - dev_network

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge
